# Максимальная длина строки
line-length = 79

[lint.per-file-ignores]
# Игнорировать F401 в init файлах
"__init__.py" = ["F401"]

[lint]
# Включить предварительный просмотр
preview = true

# Выбрать группы правил для проверки
select = ["E", "F", "I", "C90"]